import {
  SiAstonmartin,
  SiAudi,
  SiBentley,
  SiBmw,
  SiInfiniti,
  SiChevrolet,
  SiChrysler,
  SiCitroen,
  SiFerrari,
  SiFiat,
  SiFord,
  SiHonda,
  SiHyundai,
  SiJaguar,
  SiJeep,
  SiKia,
  SiLamborghini,
  SiLandrover,
  SiMaserati,
  SiMazda,
  SiMclaren,
  SiMercedes,
  SiMini,
  SiMitsubishi,
  SiNissan,
  SiPorsche,
  SiRam,
  SiRollsroyce,
  SiSubaru,
  SiTesla,
  SiToyota,
  SiVolkswagen,
  SiVolvo,
} from "react-icons/si";
import { FaCarSide } from "react-icons/fa";

export const manufacturers = [
  {icon: <FaCarSide />, label: "Any Manufacturer", value: "any_manufacturer"},
  {icon: <SiAstonmartin />, label: "Aston Martin", value: "aston_martin"},
  {icon: <SiAudi />, label: "Audi", value: "audi"},
  {icon: <SiBentley />, label: "Bentley", value: "bentley",},
  {icon: <SiBmw />, label: "BMW", value: "bMW"},
  {icon: <SiChevrolet />, label: "Chevrolet", value: "chevrolet"},
  {icon: <SiChrysler />, label: "Chrysler", value: "chrysler"},
  {icon: <SiCitroen />, label: "Citroen", value: "citroen"},
  {icon: <SiFerrari />, label: "Ferrari", value: "ferrari"},
  {icon: <SiFiat />, label: "Fiat", value: "fiat"},
  {icon: <SiFord />, label: "Ford", value: "ford"},
  {icon: <SiHonda />, label: "Honda", value: "honda"},
  {icon: <SiHyundai />, label: "Hyundai", value: "hyundai"},
  {icon: <SiInfiniti />, label: "Infiniti", value: "infiniti"},
  {icon: <SiJaguar />, label: "Jaguar", value: "jaguar"},
  {icon: <SiJeep />, label: "Jeep", value: "jeep"},
  {icon: <SiKia />, label: "Kia", value: "kia"},
  {icon: <SiLamborghini />, label: "Lamborghini", value: "lamborghini"},
  {icon: <SiLandrover />, label: "Land Rover", value: "land_rover"},
  {icon: <SiMaserati />, label: "Maserati", value: "maserati"},
  {icon: <SiMazda />, label: "Mazda", value: "mazda"},
  {icon: <SiMclaren />, label: "McLaren", value: "mclaren"},
  {icon: <SiMercedes />, label: "Mercedes-Benz", value: "mercedes_benz"},
  {icon: <SiMini />, label: "MINI", value: "mini"},
  {icon: <SiMitsubishi />, label: "Mitsubishi", value: "mitsubishi"},
  {icon: <SiNissan />, label: "Nissan", value: "nissan"},
  {icon: <SiPorsche />, label: "Porsche", value: "porsche"},
  {icon: <SiRam />, label: "Ram", value: "ram"},
  {icon: <SiRollsroyce />, label: "Rolls-Royce", value: "rolls_royce"},
  {icon: <SiSubaru />, label: "Subaru", value: "subaru"},
  {icon: <SiTesla />, label: "Tesla", value: "tesla"},
  {icon: <SiToyota />, label: "Toyota", value: "toyota"},
  {icon: <SiVolkswagen />, label: "Volkswagen", value: "volkswagen"},
  {icon: <SiVolvo />, label: "Volvo", value: "volvo"},
];

export const yearsOfProduction = [
  { label: "Any Year", value: "any_year" },
  { label: "2000", value: "2000" },
  { label: "2001", value: "2001" },
  { label: "2002", value: "2002" },
  { label: "2003", value: "2003" },
  { label: "2004", value: "2004" },
  { label: "2005", value: "2005" },
  { label: "2006", value: "2006" },
  { label: "2007", value: "2007" },
  { label: "2008", value: "2008" },
  { label: "2009", value: "2009" },
  { label: "2010", value: "2010" },
  { label: "2011", value: "2011" },
  { label: "2012", value: "2012" },
  { label: "2013", value: "2013" },
  { label: "2014", value: "2014" },
  { label: "2015", value: "2015" },
  { label: "2016", value: "2016" },
  { label: "2017", value: "2017" },
  { label: "2018", value: "2018" },
  { label: "2019", value: "2019" },
  { label: "2020", value: "2020" },
  { label: "2021", value: "2021" },
  { label: "2022", value: "2022" },
  { label: "2023", value: "2023" },
];

export const fuels = [
  { label: "Any Type", value: "any_type" },
  { label: "Gas", value: "gas" },
  { label: "Diesel", value: "diesel" },
  { label: "Electricity", value: "electricity" },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];